# Generated by Django 5.2.12 on 2026-03-30 21:54

import extra
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_id_issue',
        ),
        migrations.AddField(
            model_name='car',
            name='agency_doc',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الوكالة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم صاحب السنوية'),
        ),
    ]
