# Generated by Django 4.2.23 on 2025-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandob',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='mandob',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
    ]
