# Generated by Django 4.2.23 on 2025-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('captain', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='core.language', verbose_name='اللغات'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
    ]
