# Generated by Django 5.2.15 on 2026-07-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0003_alter_captain_city_alter_captain_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='الهاتف'),
        ),
    ]
