# Generated by Django 4.2.23 on 2025-08-11 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.IntegerField(unique=True, verbose_name='الهاتف')),
                ('city', models.CharField(max_length=200, verbose_name='المدينة')),
                ('location', models.CharField(max_length=200, verbose_name='العنوان')),
                ('max_debt', models.IntegerField(default=0, verbose_name='الحد الاقصى للدين')),
                ('image', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الصورة')),
                ('id_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية 1')),
                ('id_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية 2')),
                ('barcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='باركود')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة الباركود')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض')),
                ('latitude_base', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول للمنزل')),
                ('longitude_base', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض للمنزل')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device ID')),
                ('type', models.CharField(choices=[('user', 'زبون'), ('company', 'تاجر')], default='user', max_length=200, verbose_name='نوع الزبون')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة')),
                ('company_doc', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='شهادة تآسيس الشركة')),
                ('pin', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الهوية')),
                ('id_issue_city', models.CharField(blank=True, max_length=200, null=True, verbose_name='مكتب اصدار الهوية')),
                ('id_issue_date', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاريخ الاصدار')),
                ('id_expire_date', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاريخ النفاذ')),
                ('id_birth_date', models.DateField(blank=True, max_length=200, null=True, verbose_name='تاريخ الولادة')),
                ('house_id_issuer', models.CharField(blank=True, max_length=200, null=True, verbose_name='مكتب اصدار بطاقة السكن')),
                ('house_id_house_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الدار')),
                ('house_id_house_street', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الزقاق')),
                ('house_id_house_city', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم المحلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('is_logged', models.BooleanField(default=False, verbose_name='Is Logged')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activitytype', verbose_name='نوع النشاط')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='الدولة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language', verbose_name='اللغة')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='المحافظة')),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', extra.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_user', to='user.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'seller Token',
                'verbose_name_plural': 'sellers Tokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
